spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/entity
        username: root
        password: 998877Gk1!

    jpa:
        hibernate:
            ddl-auto: create

        properties:
            hibernate:
                default_batch_fetch_size: 100
                format_sql: true

logging.level:
    org.hibernate.SQL: debug
